### ISSUE TITLE
unmodified user data is reverted to previous value when patching

### ISSUE THREAD

**Issue by berger-n** [buda-base/editserv#18]
it's as if values that are not modified by a patch were reverted to n-1 state rather than let unmodified

1. from an initial state on user profile page after login:

![image](https://user-images.githubusercontent.com/33383857/115026414-befc9380-9ec2-11eb-8b8c-ae004ea48a14.png)

2. let's modify gender then click update:

![image](https://user-images.githubusercontent.com/33383857/115026611-ff5c1180-9ec2-11eb-9d25-8562c3e960c3.png)

(patch that is sent is ok:
![image](https://user-images.githubusercontent.com/33383857/115026842-421de980-9ec3-11eb-802b-20bce5305ece.png)
)

3. but right after updating is done we go back to old values for Area of Interest:
(these were actual values before today's several tests/modifications)

![image](https://user-images.githubusercontent.com/33383857/115026692-1569d200-9ec3-11eb-8a32-255b0493103a.png)

4. then if I modify name and submit, the name is saved but gender comes back to its previous value, before last modification:

![image](https://user-images.githubusercontent.com/33383857/115027736-5e6e5600-9ec4-11eb-9fae-49b38c8d9d86.png)

(again patch sent is ok, modifying both public and private graphs here:
![image](https://user-images.githubusercontent.com/33383857/115027620-3848b600-9ec4-11eb-9cc1-df440cc1c7fa.png)
)

**Comment by eroux** [comment]
well... that's kind of weird... it works for me, I'll take a look at the data in Fuseki

**Comment by berger-n** [comment]
seems 100% fixed to me! thanks
