### ISSUE TITLE
Integrating git repo synchronization 

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/editserv#9]
GittoDb is using the following model (http://ldspdi-dev.bdrc.io/graph/SystemGitSync.trig) in order to decide which graph should be updated, based on the gitRevision number that was set by the last commit of a repo.

In order to make this constistent across the whole buda platform, Editserv should update this model each time it commits changes to a given repo (note: buda users rdf models are not part of the data flow)  

In order to prepare this implementation, the SystemGitSync graph probably needs to be extended so it includes data about git repos, as defined here: https://github.com/buda-base/owl-schema/blob/master/adm/types/git_repos.ttl

**Comment by eroux** [comment]
I think the new format could be something like:

```trig
bdg:SystemGitSync {

   # This won't be used for now but will in the future
   bda:SystemGitSync a adm:AdminData ;
        adm:graphId         bdg:W19740 ;
        adm:randomRevision "11a3e229084349bc25d97e29393ced1d" .

   bda:GS_GR0001 a adm:GitSyncInfo ;
       adm:syncInfoForRepo  bda:GR0001 ;
       adm:syncUpToRevision "74d5bbe2b8f260cf11ac05733851a3c8d71f4444" .

...

}
```
